name: 'pg-setup'
description: 'Install PostgreSQL'
inputs:
  version:
    description: 'PostgreSQL major version number'
    required: true
  install-contrib:
    description: 'Install PostgreSQL contrib package (true/false)'
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install PostgreSQL
      run: ${{ github.action_path }}/../bin/pg-setup ${{ inputs.version }}
      shell: bash
      env:
        CONTRIB: ${{ inputs.install-contrib }}
    - name: Verify PostgreSQL Installation
      run: |
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            # Windows - check if psql is available
            if command -v psql &> /dev/null; then
              psql --version
            else
              echo "PostgreSQL installation may have failed on Windows"
              exit 1
            fi
            ;;
          *)
            # Unix-like systems
            psql --version
            ;;
        esac
      shell: bash
