name: 'pg-setup'
description: 'Install PostgreSQL'
inputs:
  version:
    description: 'PostgreSQL major version number'
    required: true
  install-contrib:
    description: 'Install PostgreSQL contrib package (true/false)'
    default: 'false'
  operating-system:
    description: 'Operating system and version to run on (e.g., ubuntu-22.04, ubuntu-24.04, macos-12, macos-14, windows-2022, windows-2025, or generic: linux, macos, windows)'
    default: 'ubuntu-24.04'
runs:
  using: "composite"
  steps:
    - name: Install PostgreSQL
      run: |
        # Get the directory of this action
        ACTION_DIR="${{ github.action_path }}"
        SCRIPT_PATH="$ACTION_DIR/../bin/pg-setup"
        
        # Ensure the script exists and is executable
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "Error: Script not found at $SCRIPT_PATH"
          exit 1
        fi
        
        # Make sure it's executable
        chmod +x "$SCRIPT_PATH"
        
        # Run the script
        "$SCRIPT_PATH" ${{ inputs.version }} ${{ inputs.operating-system }}
      shell: bash
      env:
        CONTRIB: ${{ inputs.install-contrib }}
    - name: Verify PostgreSQL Installation
      run: |
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            # Windows - check if psql is available
            if command -v psql &> /dev/null; then
              psql --version
            elif [ -f "/c/Program Files/PostgreSQL/${{ inputs.version }}/bin/psql.exe" ]; then
              "/c/Program Files/PostgreSQL/${{ inputs.version }}/bin/psql.exe" --version
            else
              echo "PostgreSQL installation may have failed on Windows"
              exit 1
            fi
            ;;
          Darwin*)
            # macOS - use full path to psql
            if [ -f "/opt/homebrew/opt/postgresql@${{ inputs.version }}/bin/psql" ]; then
              /opt/homebrew/opt/postgresql@${{ inputs.version }}/bin/psql --version
            elif [ -f "/usr/local/opt/postgresql@${{ inputs.version }}/bin/psql" ]; then
              /usr/local/opt/postgresql@${{ inputs.version }}/bin/psql --version
            else
              echo "PostgreSQL installation may have failed on macOS"
              exit 1
            fi
            ;;
          *)
            # Linux and other Unix-like systems
            psql --version
            ;;
        esac
      shell: bash
