name: 'build-check'
description: 'Build & install the extension and run regression tests'
inputs:
  working-directory:
    description: 'Working directory'
  operating-system:
    description: 'Operating system and version to run on (e.g., ubuntu-22.04, ubuntu-24.04, macos-12, macos-14, windows-2022, windows-2025, or generic: linux, macos, windows)'
    default: 'ubuntu-24.04'
runs:
  using: "composite"
  steps:
    - name: Build and Test Extension
      run: |
        # Get the directory of this action
        ACTION_DIR="${{ github.action_path }}"
        SCRIPT_PATH="$ACTION_DIR/../bin/build-check"
        
        # Ensure the script exists and is executable
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "Error: Script not found at $SCRIPT_PATH"
          exit 1
        fi
        
        # Make sure it's executable
        chmod +x "$SCRIPT_PATH"
        
        # Run the script
        "$SCRIPT_PATH" ${{ inputs.operating-system }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Verify Installation
      run: |
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            # Windows - check if extension was built
            if find . -maxdepth 1 -name "*.dll" -o -name "*.so" | grep -q .; then
              echo "Extension built successfully on Windows"
            else
              echo "Extension build may have failed on Windows"
              exit 1
            fi
            ;;
          Darwin*)
            # macOS - check for .dylib files in current directory and PostgreSQL lib directory
            echo "Looking for extension files on macOS..."
            echo "Current directory files:"
            find . -maxdepth 1 -name "*.dylib" -o -name "*.so" | head -5
            echo "PostgreSQL lib directory files:"
            find /opt/homebrew/lib/postgresql* -name "*.dylib" 2>/dev/null | head -5 || true
            find /usr/local/lib/postgresql* -name "*.dylib" 2>/dev/null | head -5 || true
            
            if find . -maxdepth 1 -name "*.dylib" -o -name "*.so" | grep -q .; then
              echo "Extension built successfully on macOS (found in current directory)"
            elif find /opt/homebrew/lib/postgresql* -name "*.dylib" 2>/dev/null | grep -q .; then
              echo "Extension built successfully on macOS (found in Homebrew lib directory)"
            elif find /usr/local/lib/postgresql* -name "*.dylib" 2>/dev/null | grep -q .; then
              echo "Extension built successfully on macOS (found in local lib directory)"
            else
              echo "Extension build may have failed on macOS"
              echo "Available files in current directory:"
              ls -la *.dylib *.so 2>/dev/null || echo "No .dylib or .so files found in current directory"
              exit 1
            fi
            ;;
          *)
            # Linux and other Unix-like systems - check for .so files
            if find . -maxdepth 1 -name "*.so" | grep -q .; then
              echo "Extension built successfully"
            else
              echo "Extension build may have failed"
              exit 1
            fi
            ;;
        esac
      shell: bash
      working-directory: ${{ inputs.working-directory }}
