name: 'build-check'
description: 'Build & install the extension and run regression tests'
inputs:
  working-directory:
    description: 'Working directory'
runs:
  using: "composite"
  steps:
    - name: Build and Test Extension
      run: |
        # Get the directory of this action
        ACTION_DIR="${{ github.action_path }}"
        SCRIPT_PATH="$ACTION_DIR/../bin/build-check"
        
        # Ensure the script exists and is executable
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "Error: Script not found at $SCRIPT_PATH"
          exit 1
        fi
        
        # Make sure it's executable
        chmod +x "$SCRIPT_PATH"
        
        # Run the script
        "$SCRIPT_PATH"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Verify Installation
      run: |
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            # Windows - check if extension was built
            if find . -maxdepth 1 -name "*.dll" -o -name "*.so" | grep -q .; then
              echo "Extension built successfully on Windows"
            else
              echo "Extension build may have failed on Windows"
              exit 1
            fi
            ;;
          *)
            # Unix-like systems
            if find . -maxdepth 1 -name "*.so" | grep -q .; then
              echo "Extension built successfully"
            else
              echo "Extension build may have failed"
              exit 1
            fi
            ;;
        esac
      shell: bash
      working-directory: ${{ inputs.working-directory }}
