name: 'build-check'
description: 'Build & install the extension and run regression tests'
inputs:
  working-directory:
    description: 'Working directory'
runs:
  using: "composite"
  steps:
    - name: Build and Test Extension
      run: ${{ github.action_path }}/../bin/build-check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Verify Installation
      run: |
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            # Windows - check if extension was built
            if [ -f "*.dll" ] || [ -f "*.so" ]; then
              echo "Extension built successfully on Windows"
            else
              echo "Extension build may have failed on Windows"
              exit 1
            fi
            ;;
          *)
            # Unix-like systems
            if [ -f "*.so" ]; then
              echo "Extension built successfully"
            else
              echo "Extension build may have failed"
              exit 1
            fi
            ;;
        esac
      shell: bash
      working-directory: ${{ inputs.working-directory }}
