name: 'update-check'
description: 'Verify that update script works'
inputs:
  working-directory:
    description: 'Working directory'
  main-branch:
    description: 'Branch containing version to update from'
runs:
  using: "composite"
  steps:
    - name: Check Extension Updates
      run: |
        # Get the directory of this action
        ACTION_DIR="${{ github.action_path }}"
        SCRIPT_PATH="$ACTION_DIR/../bin/update-check"
        
        # Ensure the script exists and is executable
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "Error: Script not found at $SCRIPT_PATH"
          exit 1
        fi
        
        # Make sure it's executable
        chmod +x "$SCRIPT_PATH"
        
        # Run the script
        "$SCRIPT_PATH"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        EXT_BRANCH: ${{ inputs.main-branch }}
    - name: Verify Update Check
      run: |
        echo "Update check completed successfully"
        case "$(uname -s)" in
          CYGWIN*|MINGW*|MSYS*)
            echo "Update check ran on Windows"
            ;;
          Darwin*)
            echo "Update check ran on macOS"
            ;;
          Linux*)
            echo "Update check ran on Linux"
            ;;
          *)
            echo "Update check ran on unknown OS"
            ;;
        esac
      shell: bash
      working-directory: ${{ inputs.working-directory }}
